In [1]:
import xml.etree.ElementTree as ET
import numpy as np
from scipy.spatial.transform import Rotation as R

FILE_PATH = r"C:\Users\cgokmen\Downloads\scenes\scenes\Beechwood_0_garden\urdf\Beechwood_0_garden_best.urdf"

# Get the joint axes in the object
with open(FILE_PATH) as f:
  tree = ET.parse(f)
joints = list(tree.findall('.//joint'))

states = {}
for joint in joints:
  name = joint.attrib['name'].replace("j_", "").replace("-", "_")
  position = np.array([float(x) for x in joint.find('origin').attrib['xyz'].split(" ")])
  orientation = np.array([float(x) for x in joint.find('origin').attrib['rpy'].split(" ")])
  states[name] = (position, R.from_euler("xyz", orientation).as_quat())

In [14]:
states

{'countertop_jveutp_0': (array([-3.80148503, 11.83083303,  0.86036084]),
  array([ 0.        ,  0.        , -0.36342162,  0.93162478])),
 'armchair_bslhmj_0': (array([-5.97972926, 22.63464597,  0.4247163 ]),
  array([0.        , 0.        , 0.3807997 , 0.92465755])),
 'armchair_vzhxuf_0': (array([-2.98129124, 22.70649003,  0.42499755]),
  array([ 0.        ,  0.        , -0.29510126,  0.95546598])),
 'bottom_cabinet_qacthv_0': (array([ 5.48809149, 12.21836768,  0.14964406]),
  array([ 0.        ,  0.        , -0.70710666,  0.7071069 ])),
 'breakfast_table_dnsjnv_0': (array([-5.1093457 , 16.68582422,  0.37762405]),
  array([0., 0., 0., 1.])),
 'breakfast_table_skczfi_0': (array([ 1.84065027, 13.83657422,  0.34881591]),
  array([0., 0., 0., 1.])),
 'breakfast_table_skczfi_1': (array([-4.24934961, 23.39686328,  0.37373192]),
  array([0., 0., 0., 1.])),
 'breakfast_table_skczfi_2': (array([-2.40424699, 22.38633099,  0.2491538 ]),
  array([ 0.        ,  0.        , -0.09853775,  0.99513331]